### ISSUE TITLE
Address didInsertElement deprecation

### ISSUE THREAD

**Issue by crodriguez1a** [crodriguez1a/ember-themed-syntax#11]
https://github.com/crodriguez1a/ember-themed-syntax/blob/13910005c187eb035e931babf295c9204c121f98/addon/components/themed-syntax.js#L140

**Comment by jacobq** [comment]
What is deprecated here? Surely not [the `didInsertElement()` hook itself](https://guides.emberjs.com/v2.18.0/components/the-component-lifecycle/#toc_integrating-with-third-party-libraries-with-code-didinsertelement-code). Could you please include the deprecation warning message and/or a link to the specific deprecation [on the official page](https://emberjs.com/deprecations/v2.x/)?

**Comment by crodriguez1a** [comment]
@jacobq I honestly can't remember what this issue was about, and my documentation isn't great. I'll close this and reopen if/when it merits attention.
