### ISSUE TITLE
Extra opening & closing space?

### ISSUE THREAD

**Issue by samselikoff** [crodriguez1a/ember-themed-syntax#4]
Awesome addon!!

It seems like there's an extra space at the beginning and ending of each block. Is this intentional, or a bug?

**Comment by crodriguez1a** [comment]
@samselikoff Thanks man!!

The extra spaces are not intentional. It might be a side effect of the line numbers css. I'll take a look.

**Comment by crodriguez1a** [comment]
@samselikoff FYI, there is an intentional line break at the beginning and end of each block (to help with readability). I'll make that optional on this next update.

**Comment by crodriguez1a** [comment]
@samselikoff These items should be resolved with #0.0.6. Let me know if any issues persist.

**Comment by samselikoff** [comment]
Sweet - thanks!
